name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          # Get the list of changed files between the last commit and the current commit
          git diff --name-only HEAD~2 HEAD > changed_files.txt

      - name: Show changed files
        run: |
          cat changed_files.txt
