name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        run: |
          # Fetch all commits from the remote
          git fetch --prune --unshallow
          # Get the list of changed files between the last commit and the current commit
          git diff --name-only HEAD^ HEAD > changed_files.txt

      - name: Show changed files
        run: |
          cat changed_files.txt
