name: Check Last Two Commit Changes

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code and fetch the full commit history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # List the files changed in the last two commits and save to a file
      - name: List changed files in the last two commits
        run: |
          git diff --name-only HEAD~2 HEAD > changed_files.txt
          cat changed_files.txt

      # Extract and print folder names using awk
      - name: Extract folder names using awk
        run: |
          awk -F'/' '{print $1}' changed_files.txt | sort -u > folders.txt

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Build and push Docker images for each folder
      - name: Build and push Docker images
        run: |
          while read folder; do
           if [ "$folder" != ".github" ]; then
            echo "Building and pushing Docker image for folder: $folder"
            cd $folder

            # Build Docker image
            docker build -t $folder .

            # Tag the image with ECR repository URL
            docker tag $folder:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:$folder

            # Log in to ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            # Push the Docker image to ECR
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:$folder

            cd ..
          fi
          done < folders.txt
