name: Check Last Two Commit Changes

on:
  push:
    branches:
      - main  # Change to your default branch if needed
  pull_request:
    branches:
      - main  # Change to your default branch if needed

jobs:
  check-changes:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code and fetch the full commit history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This fetches the full commit history
      
      # List the files changed in the last two commits and save to a file
      - name: List changed files in the last two commits
        run: |
          git diff --name-only HEAD~2 HEAD > changed_files.txt
          cat changed_files.txt
      
      # Extract and print folder names using awk
      - name: Extract folder names using awk
        run: |
          awk -F'/' '{print $1}' changed_files.txt | sort -u
